import 'package:json_annotation/json_annotation.dart';
import '/config/constants.dart';
import 'calendar_color.dart';
import 'calendar_dates_converter.dart';
import 'calendar_date.dart';
import 'date_time_converter.dart';

part 'calendar.g.dart';

// WARNING you must re-run `flutter pub run build_runner build` when updating
// this file!

@JsonSerializable()
@CalendarDatesConverter()
@DateTimeConverter()
class Calendar {
  @JsonKey(includeIfNull: false)
  int? id; // optional because this is generated by the backend

  @JsonKey(name: 'user_id')
  String? userID;

  String name;

  @JsonKey(name: 'color', required: true)
  String colorHex;

  @JsonKey(name: 'background_slug', required: true)
  String backgroundSlug;

  // needs to be optional because when we save this, includeIfNull must allow
  // this field to be omitted
  @JsonKey(name: 'calendar_dates', required: false, includeIfNull: false)
  CalendarDates? dates;

  @JsonKey(ignore: true)
  CalendarColor get color => colors.firstWhere((e) => colorHex == e.hex);

  Calendar(
      {this.id,
      this.userID,
      required this.name,
      required this.colorHex,
      required this.backgroundSlug,
      this.dates});

  factory Calendar.blank() {
    return Calendar(
        name: 'Untitled',
        colorHex: colors.first.hex,
        backgroundSlug: 'darts@3x.png');
  }

  factory Calendar.fromJson(Map<String, dynamic> json) =>
      _$CalendarFromJson(json);
  Map<String, dynamic> toJson() => _$CalendarToJson(this);
}
